version: "3.1"

services:

  graphsense-dashboard:
    image: graphsense-dashboard
    build:
      context: graphsense-dashboard
    ports:
      - "$DASHBOARD_PORT:8000"
    environment:
      REST_ENDPOINT: "${REST_ENDPOINT}"
      TITANIUM_REPORT_GENERATION_URL: "${TITANIUM_REPORT_GENERATION_URL}"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
