version: "3.5"

services:

  bitcoin-client:
    image: bitcoin
    container_name: bitcoin
    hostname: bitcoin
    build:
      context: btc-client
    volumes:
      - ${BTC_BLOCK_DATADIR}:/opt/graphsense/data
      - ${BTC_CLIENT_CONF}:/opt/graphsense/client.conf
    networks:
      - graphsense-net
    ports:
      - 8332:8332
    restart: always

  bitcoin-cash-client:
    image: bitcoin-cash
    container_name: bitcoin-cash
    hostname: bitcoin-cash
    build:
      context: bch-client
    volumes:
      - ${BCH_BLOCK_DATADIR}:/opt/graphsense/data
      - ${BCH_CLIENT_CONF}:/opt/graphsense/client.conf
    networks:
      - graphsense-net
    ports:
      - 8432:8432
    restart: always

  litecoin-client:
    image: litecoin
    container_name: litecoin
    hostname: litecoin
    build:
      context: ltc-client
    volumes:
      - ${LTC_BLOCK_DATADIR}:/opt/graphsense/data
      - ${LTC_CLIENT_CONF}:/opt/graphsense/client.conf
    networks:
      - graphsense-net
    ports:
      - 8532:8532
    restart: always

  zcash-client:
    image: zcash
    container_name: zcash
    hostname: zcash
    build:
      context: zec-client
    volumes:
      - ${ZEC_BLOCK_DATADIR}:/opt/graphsense/data
      - ${ZEC_CLIENT_CONF}:/opt/graphsense/client.conf
    networks:
      - graphsense-net
    ports:
      - 8632:8632
    restart: always

  ethereum-client:
    image: openethereum
    container_name: openethereum
    hostname: openethereum
    build:
      context: eth-client
    volumes:
      - ${ETH_BLOCK_DATADIR}:/home/dockeruser/openethereum
      - ./eth-client/config.toml:/home/dockeruser/.local/share/io.parity.ethereum/config.toml
    networks:
      - graphsense-net
    ports:
      - 8545:8545
    restart: always


networks:
  graphsense-net:
    name: graphsense-global-net
