version: "3.1"

services:

  graphsense-rest:
    image: graphsense-rest
    build:
      context: graphsense-rest
      args:
        NUM_WORKERS: "${NUM_WORKERS}"
    ports:
      - "${REST_PORT}:9000"
    restart: always
